version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "UTC"
    commit-message:
      prefix: "[Dependabot]"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    versioning-strategy: "auto"